-- 부하 테스트 종료 후 데이터 정합성 검증 스크립트
-- DB per service 분리로 서비스별 MySQL 인스턴스가 다르다.
-- 각 CHECK는 해당 서비스의 MySQL 인스턴스에 연결해서 실행해야 한다.
--
-- payment-api (3307):  CHECK_1, CHECK_4, CHECK_5a, CHECK_2a/2b count
-- ledger-service (308): CHECK_3, CHECK_5b, CHECK_2a/2b count
--
-- 실행 예시:
--   mysql -h 127.0.0.1 -P 3307 -u jpay -pjpay < load-tests/verify/consistency-check-payment.sql
--   mysql -h 127.0.0.1 -P 3308 -u jpay -pjpay < load-tests/verify/consistency-check-ledger.sql
-- 모든 쿼리 결과가 0 이어야 정합성 통과